-- quotes.lua — Simple UI
-- Quote database for the Desktop "Quote of the Day" module.
-- Edit freely: add, remove or replace entries in the same format.
-- Format: { q = "Quote text.", a = "Author", b = "Book title (optional)" }

return {

    -- Fiction
    { q = "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", a = "Jane Austen", b = "Pride and Prejudice" },
    { q = "All happy families are alike; each unhappy family is unhappy in its own way.", a = "Leo Tolstoy", b = "Anna Karenina" },
    { q = "It was the best of times, it was the worst of times.", a = "Charles Dickens", b = "A Tale of Two Cities" },
    { q = "Call me Ishmael.", a = "Herman Melville", b = "Moby-Dick" },
    { q = "So we beat on, boats against the current, borne back ceaselessly into the past.", a = "F. Scott Fitzgerald", b = "The Great Gatsby" },
    { q = "It does not do to dwell on dreams and forget to live.", a = "J.K. Rowling", b = "Harry Potter and the Philosopher's Stone" },
    { q = "There is no greater agony than bearing an untold story inside you.", a = "Maya Angelou", b = "I Know Why the Caged Bird Sings" },
    { q = "The world is a book, and those who do not travel read only one page.", a = "Saint Augustine" },
    { q = "Not all those who wander are lost.", a = "J.R.R. Tolkien", b = "The Fellowship of the Ring" },
    { q = "Even the darkest night will end and the sun will rise.", a = "Victor Hugo", b = "Les Misérables" },
    { q = "To infinity and beyond.", a = "Buzz Lightyear" },
    { q = "It's the possibility of having a dream come true that makes life interesting.", a = "Paulo Coelho", b = "The Alchemist" },
    { q = "When you want something, all the universe conspires in helping you to achieve it.", a = "Paulo Coelho", b = "The Alchemist" },
    { q = "A reader lives a thousand lives before he dies. The man who never reads lives only one.", a = "George R.R. Martin" },
    { q = "There is no friend as loyal as a book.", a = "Ernest Hemingway" },
    { q = "I am not afraid of storms, for I am learning how to sail my ship.", a = "Louisa May Alcott", b = "Little Women" },
    { q = "The only way out of the labyrinth of suffering is to forgive.", a = "John Green", b = "Looking for Alaska" },
    { q = "Some infinities are bigger than other infinities.", a = "John Green", b = "The Fault in Our Stars" },
    { q = "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", a = "Dr. Seuss", b = "I Can Read With My Eyes Shut!" },
    { q = "Fantasy is hardly an escape from reality. It's a way of understanding it.", a = "Lloyd Alexander" },
    { q = "There is nothing either good or bad, but thinking makes it so.", a = "William Shakespeare", b = "Hamlet" },
    { q = "We accept the love we think we deserve.", a = "Stephen Chbosky", b = "The Perks of Being a Wallflower" },
    { q = "It's only after we've lost everything that we're free to do anything.", a = "Chuck Palahniuk", b = "Fight Club" },
    { q = "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", a = "J.K. Rowling", b = "Harry Potter and the Prisoner of Azkaban" },
    { q = "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", a = "J.K. Rowling" },
    { q = "The journey of a thousand miles begins with a single step.", a = "Lao Tzu" },
    { q = "Whatever our souls are made of, his and mine are the same.", a = "Emily Brontë", b = "Wuthering Heights" },
    { q = "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", a = "Sylvia Plath", b = "The Bell Jar" },
    { q = "We are all just walking each other home.", a = "Ram Dass" },
    { q = "It is our choices that show what we truly are, far more than our abilities.", a = "J.K. Rowling", b = "Harry Potter and the Chamber of Secrets" },

    -- Philosophy and wisdom
    { q = "Be yourself; everyone else is already taken.", a = "Oscar Wilde" },
    { q = "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", a = "Albert Einstein" },
    { q = "A room without books is like a body without a soul.", a = "Marcus Tullius Cicero" },
    { q = "So many books, so little time.", a = "Frank Zappa" },
    { q = "In three words I can sum up everything I've learned about life: it goes on.", a = "Robert Frost" },
    { q = "To live is the rarest thing in the world. Most people exist, that is all.", a = "Oscar Wilde" },
    { q = "We are all alone, born alone, die alone.", a = "Hunter S. Thompson" },
    { q = "Not all readers are leaders, but all leaders are readers.", a = "Harry S. Truman" },
    { q = "I have always imagined that Paradise will be a kind of library.", a = "Jorge Luis Borges" },
    { q = "Think before you speak. Read before you think.", a = "Fran Lebowitz" },
    { q = "The man who does not read has no advantage over the man who cannot read.", a = "Mark Twain" },
    { q = "One must always be careful of books, and what is inside them, for words have the power to change us.", a = "Cassandra Clare", b = "City of Bones" },
    { q = "You only live once, but if you do it right, once is enough.", a = "Mae West" },
    { q = "Be the change that you wish to see in the world.", a = "Mahatma Gandhi" },
    { q = "If you tell the truth, you don't have to remember anything.", a = "Mark Twain" },
    { q = "A friend is someone who knows all about you and still loves you.", a = "Elbert Hubbard" },
    { q = "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", a = "Ralph Waldo Emerson" },
    { q = "We must not allow other people's limited perceptions to define us.", a = "Virginia Satir" },
    { q = "Life is what happens to us while we are making other plans.", a = "Allen Saunders" },
    { q = "The purpose of our lives is to be happy.", a = "Dalai Lama" },
    { q = "Get busy living or get busy dying.", a = "Stephen King", b = "Different Seasons" },
    { q = "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", a = "Marilyn Monroe" },
    { q = "It is never too late to be what you might have been.", a = "George Eliot" },

    -- Reading and writing
    { q = "A book must be the axe for the frozen sea within us.", a = "Franz Kafka" },
    { q = "Books are mirrors: we only see in them what we already have inside us.", a = "Carlos Ruiz Zafón", b = "The Shadow of the Wind" },
    { q = "You don't have to burn books to destroy a culture. Just get people to stop reading them.", a = "Ray Bradbury" },
    { q = "Until I feared I would lose it, I never loved to read. One does not love breathing.", a = "Harper Lee", b = "To Kill a Mockingbird" },
    { q = "I declare after all there is no enjoyment like reading!", a = "Jane Austen", b = "Pride and Prejudice" },
    { q = "Reading is essential for those who seek to rise above the ordinary.", a = "Jim Rohn" },
    { q = "I am a part of all that I have met.", a = "Alfred Lord Tennyson" },
    { q = "If you only read the books that everyone else is reading, you can only think what everyone else is thinking.", a = "Haruki Murakami", b = "Norwegian Wood" },
    { q = "Books are the carriers of civilization.", a = "Barbara Tuchman" },
    { q = "A book is a dream that you hold in your hands.", a = "Neil Gaiman" },
    { q = "No two persons ever read the same book.", a = "Edmund Wilson" },
    { q = "I would be most content if my children grew up to be the kind of people who think decorating consists mostly of building enough bookshelves.", a = "Anna Quindlen" },
    { q = "Outside of a dog, a book is a man's best friend. Inside of a dog it's too dark to read.", a = "Groucho Marx" },
    { q = "Classic — a book which people praise and don't read.", a = "Mark Twain" },
    { q = "The world belongs to those who read.", a = "Rick Holland" },
    { q = "Reading is a conversation. All books talk. But a good book listens as well.", a = "Mark Haddon" },
    { q = "Writing is the painting of the voice.", a = "Voltaire" },
    { q = "A writer only begins a book. A reader finishes it.", a = "Samuel Johnson" },
    { q = "You can never get a cup of tea large enough or a book long enough to suit me.", a = "C.S. Lewis" },
    { q = "Sleep is good, he said, and books are better.", a = "George R.R. Martin", b = "A Clash of Kings" },

    -- Love and relationships
    { q = "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love.", a = "Gabriel García Márquez", b = "Love in the Time of Cholera" },
    { q = "I love you without knowing how, or when, or from where. I love you simply, without problems or pride.", a = "Pablo Neruda" },
    { q = "The best love is the kind that awakens the soul and makes us reach for more.", a = "Nicholas Sparks", b = "The Notebook" },
    { q = "You had me at hello.", a = "Cameron Crowe", b = "Jerry Maguire" },
    { q = "To love at all is to be vulnerable.", a = "C.S. Lewis", b = "The Four Loves" },
    { q = "The greatest thing you'll ever learn is just to love, and be loved in return.", a = "eden ahbez" },
    { q = "Where there is love there is life.", a = "Mahatma Gandhi" },
    { q = "I am who I am because of you. You are every reason, every hope, and every dream I've ever had.", a = "Nicholas Sparks", b = "The Notebook" },
    { q = "There is only one happiness in this life, to love and be loved.", a = "George Sand" },

    -- Life and perseverance
    { q = "In the middle of every difficulty lies opportunity.", a = "Albert Einstein" },
    { q = "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", a = "Maya Angelou" },
    { q = "Do not go gentle into that good night.", a = "Dylan Thomas" },
    { q = "The only way to do great work is to love what you do.", a = "Steve Jobs" },
    { q = "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", a = "Martin Luther King Jr." },
    { q = "In the end, it's not the years in your life that count. It's the life in your years.", a = "Abraham Lincoln" },
    { q = "It does not matter how slowly you go as long as you do not stop.", a = "Confucius" },
    { q = "The secret of getting ahead is getting started.", a = "Mark Twain" },
    { q = "Success is not final, failure is not fatal: it is the courage to continue that counts.", a = "Winston Churchill" },
    { q = "Believe you can and you're halfway there.", a = "Theodore Roosevelt" },
    { q = "You miss 100% of the shots you don't take.", a = "Wayne Gretzky" },
    { q = "Whether you think you can or you think you can't, you're right.", a = "Henry Ford" },
    { q = "The only impossible journey is the one you never begin.", a = "Tony Robbins" },
    { q = "It always seems impossible until it's done.", a = "Nelson Mandela" },
    { q = "Don't watch the clock; do what it does. Keep going.", a = "Sam Levenson" },
    { q = "Keep your face always toward the sunshine—and shadows will fall behind you.", a = "Walt Whitman" },

}
