-- i18n.lua — Simple UI
-- Translation loader.
--
-- COMO FUNCIONA
-- O KOReader usa require("gettext") em todos os módulos, capturando a função
-- como variável local no topo de cada ficheiro. Substituir _G["_"] depois
-- disso não tem efeito nessas variáveis locais já capturadas.
--
-- A solução correcta é substituir package.loaded["gettext"] com um wrapper
-- ANTES de qualquer outro módulo do plugin ser carregado. Assim, todos os
-- require("gettext") subsequentes recebem o wrapper automaticamente.
--
-- install() deve ser a PRIMEIRA chamada em main.lua, antes de qualquer require().
--
-- HOW TO ADD A LANGUAGE
--   1. Copy locale/simpleui.pot → locale/<lang>.po  (e.g. locale/de.po)
--   2. Fill in the msgstr values.
--   3. Done — no code changes needed.

local logger = require("logger")

-- Locate the plugin directory from this file's path.
local _dir = (debug.getinfo(1, "S").source:match("^@(.+/)") or "./")

-- ---------------------------------------------------------------------------
-- .po parser — minimal, handles the subset generated by simpleui.pot
-- ---------------------------------------------------------------------------
local function parsePO(path)
    local f = io.open(path, "r")
    if not f then return nil end

    local map = {}
    local msgid, msgstr, in_id, in_str = nil, nil, false, false

    local function flush()
        if msgid and msgstr and msgid ~= "" and msgstr ~= "" then
            map[msgid] = msgstr
        end
        msgid, msgstr, in_id, in_str = nil, nil, false, false
    end

    local function unescape(s)
        return s:gsub("\\n", "\n"):gsub("\\t", "\t"):gsub('\\"', '"'):gsub("\\\\", "\\")
    end

    for line in f:lines() do
        line = line:match("^%s*(.-)%s*$")
        if line:match("^#") or line == "" then
            if line == "" then flush() end
        elseif line:match('^msgid%s+"') then
            flush()
            msgid  = unescape(line:match('^msgid%s+"(.*)"'))
            in_id  = true; in_str = false
        elseif line:match('^msgstr%s+"') then
            msgstr = unescape(line:match('^msgstr%s+"(.*)"'))
            in_str = true; in_id  = false
        elseif line:match('^"') then
            local cont = unescape(line:match('^"(.*)"'))
            if in_id  and msgid  then msgid  = msgid  .. cont end
            if in_str and msgstr then msgstr = msgstr .. cont end
        end
    end
    flush()
    f:close()
    return map
end

-- ---------------------------------------------------------------------------
-- Language detection
-- ---------------------------------------------------------------------------
local function detectLang()
    local lang = G_reader_settings and G_reader_settings:readSetting("language")
    if type(lang) == "string" and lang ~= "" then return lang end
    local lc = os.getenv("LANG") or os.getenv("LC_ALL") or os.getenv("LC_MESSAGES") or ""
    lang = lc:match("^([a-zA-Z_]+)")
    return lang or "en"
end

-- ---------------------------------------------------------------------------
-- Load translation table
-- ---------------------------------------------------------------------------
local _translations = nil

local function loadTranslations()
    local lang = detectLang()
    if lang == "en" or lang:match("^en_") then return nil end

    local function try(name)
        local path = _dir .. "locale/" .. name .. ".po"
        local t = parsePO(path)
        if t and next(t) then
            local n = 0; for _ in pairs(t) do n = n + 1 end
            logger.info("simpleui i18n: loaded " .. path .. " — " .. n .. " strings")
            return t
        end
    end

    return try(lang) or (function()
        local prefix = lang:match("^([a-zA-Z]+)")
        if prefix and prefix ~= lang then return try(prefix) end
    end)()
end

-- ---------------------------------------------------------------------------
-- install() — substitui package.loaded["gettext"] com um wrapper.
-- Deve ser chamado ANTES de qualquer require() dos módulos do plugin.
-- ---------------------------------------------------------------------------
local _installed = false

local function install()
    if _installed then return end

    _translations = loadTranslations()
    if not _translations then return end  -- língua não suportada ou inglês

    local orig_gettext = package.loaded["gettext"]
    if not orig_gettext then
        -- gettext ainda não foi carregado — carregar agora para poder fazer wrap
        local ok, gt = pcall(require, "gettext")
        if not ok or not gt then
            logger.warn("simpleui i18n: cannot load gettext, translations disabled")
            return
        end
        orig_gettext = gt
    end

    -- Criar wrapper que intercepta strings do plugin
    -- e delega tudo o resto para o gettext original do KOReader.
    local wrapper
    local mt = getmetatable(orig_gettext)
    if mt and mt.__call then
        -- gettext é uma tabela com __call — criar wrapper com o mesmo metamétodo
        wrapper = setmetatable({}, {
            __call = function(_, msgid)
                local t = _translations[msgid]
                if t then return t end
                return orig_gettext(msgid)
            end,
            __index = orig_gettext,  -- preservar outros métodos (bindTextDomain, etc.)
        })
    elseif type(orig_gettext) == "function" then
        -- gettext é uma função directa
        wrapper = function(msgid)
            local t = _translations[msgid]
            if t then return t end
            return orig_gettext(msgid)
        end
    else
        logger.warn("simpleui i18n: unexpected gettext type: " .. type(orig_gettext))
        return
    end

    package.loaded["gettext"] = wrapper
    _installed = true
    logger.info("simpleui i18n: installed wrapper for language: " .. detectLang())
end

-- ---------------------------------------------------------------------------
-- uninstall() — restaura o gettext original ao fazer teardown do plugin.
-- ---------------------------------------------------------------------------
local function uninstall()
    if not _installed then return end
    -- Recarregar o gettext original a partir do sistema de ficheiros
    -- (limpar da cache e deixar o próximo require() recarregar normalmente)
    package.loaded["gettext"] = nil
    pcall(require, "gettext")  -- recarrega e repõe em package.loaded
    _installed    = false
    _translations = nil
    logger.info("simpleui i18n: uninstalled")
end

return {
    install   = install,
    uninstall = uninstall,
    getLang   = detectLang,
}
